### ISSUE TITLE
Fix failing unit test schema/transactions.js

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1127]
### Expected behavior
All tests should pass.

### Actual behavior
```
 7 failing

  1) transactions
       getTransactions
         should return error when senderPublicKeys is not an array:

      AssertionError: expected [ Array(3) ] to deeply equal [ Array(1) ]
      + expected - actual

       [
         "Expected type array but found type string"
      -  "Expected type array but found type string"
      -  "Expected type array but found type string"
       ]
      
      at Context.<anonymous> (test/unit/schema/transactions.js:76:11)

  2) transactions
       getTransactions
         should return error when senderPublicKeys length is less than minimum acceptable length:

      AssertionError: expected [ Array(3) ] to deeply equal [ 'Array is too short (0), minimum 1' ]
      + expected - actual

       [
      -  "Expected type array but found type string"
      -  "Expected type array but found type string"
      -  "Expected type array but found type string"
      +  "Array is too short (0), minimum 1"
       ]
      
      at Context.<anonymous> (test/unit/schema/transactions.js:84:11)

  3) transactions
       getTransactions
         should return error when recipientPublicKeys is not an array:

      AssertionError: expected [ Array(3) ] to deeply equal [ Array(1) ]
      + expected - actual

       [
         "Expected type array but found type string"
      -  "Expected type array but found type string"
      -  "Expected type array but found type string"
       ]
      
      at Context.<anonymous> (test/unit/schema/transactions.js:92:11)

  4) transactions
       getTransactions
         should return error when recipientPublicKeys length is less than minimum acceptable length:

      AssertionError: expected [ Array(3) ] to deeply equal [ 'Array is too short (0), minimum 1' ]
      + expected - actual

       [
      -  "Expected type array but found type string"
      -  "Expected type array but found type string"
      -  "Expected type array but found type string"
      +  "Array is too short (0), minimum 1"
       ]
      
      at Context.<anonymous> (test/unit/schema/transactions.js:100:11)

  5) transactions
       getTransactions
         should return error when recipientIds is not an array:

      AssertionError: expected [ Array(3) ] to deeply equal [ Array(1) ]
      + expected - actual

       [
         "Expected type array but found type string"
      -  "Expected type array but found type string"
      -  "Expected type array but found type string"
       ]
      
      at Context.<anonymous> (test/unit/schema/transactions.js:108:11)

  6) transactions
       getTransactions
         should return error when recipientIds length is less than minimum acceptable length:

      AssertionError: expected [ Array(3) ] to deeply equal [ 'Array is too short (0), minimum 1' ]
      + expected - actual

       [
      -  "Expected type array but found type string"
      -  "Expected type array but found type string"
      -  "Expected type array but found type string"
      +  "Array is too short (0), minimum 1"
       ]
      
      at Context.<anonymous> (test/unit/schema/transactions.js:116:11)

  7) transactions
       getTransactions
         should be ok when params field length valid:
     AssertionError: expected [ Array(3) ] to not exist
      at Context.<anonymous> (test/unit/schema/transactions.js:121:44)
```

### Steps to reproduce:
https://github.com/LiskHQ/lisk/blob/91aae7e113022c08acc84d3f93a8796e0450cbc1/test/unit/schema/transactions.js#L33
Remove skip tag on the failing test and execute it:
`mocha test/unit/schema/transactions.js`

**Comment by karmacoma** [comment]
We are going to review unused z-schema definitions and move the remaining to swagger definitions. Therefore these tests will be removed.
