### ISSUE TITLE
Bug on schema migrations from 1.0.0 to 972 branch

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1146]
Migrations introduced by 972 branch fail on the next point when applying over an existing database schema from v1.0.0:

```
[ERR] 2017-12-13 16:30:27 | Error: ERROR:  column "block_id" does not exist
LINE 1: SELECT "block_id" AS id FROM blocks WHERE "block_id" = '6524...
               ^

    at Client._readError (/Users/diego-g/git/lisk/node_modules/pg-native/index.js:80:13)
    at Client._read (/Users/diego-g/git/lisk/node_modules/pg-native/index.js:121:19)
    at emitNone (events.js:86:13)
    at PQ.emit (events.js:185:7)
    at PQ.EventEmitter.emit (/Users/diego-g/git/lisk/node_modules/sc-domain/index.js:12:31)
```

**Comment by LucasIsasmendi** [comment]
Closed by #1169
