### ISSUE TITLE
Review eslint targets

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1209]
Due to the addition and removal of various sub-directories in `1.0.0.` The currently defined target list is outdated, meaning a number of files are not being linted.

https://github.com/LiskHQ/lisk/blob/2bfcc2e85da1c9d88cd2e1e51f399cbd6a1757d1/Gruntfile.js#L119-L128

The missing entries are:

- `app.js`
- `config/`
- `db/`
- `Gruntfile.js`
- `webpack.config.js`
- `workersController.js`

**NOTE:** For the root level files we can just add `*.js`.

**Comment by karmacoma** [comment]
Luckily, if we update the targets we only get the following errors:

```
Running "eslint:target" (eslint) task
error: 'gc' is not defined (no-undef) at app.js:58:3:
  56 | if (typeof gc !== 'undefined') {
  57 | 	setInterval(function () {
> 58 | 		gc();
     | 		^
  59 | 	}, 60000);
  60 | }
  61 | 


error: Missing semicolon (semi) at Gruntfile.js:70:41:
  68 | 						var slowTag = '';
  69 | 						if (tag !== 'slow') {
> 70 | 							slowTag = '--grep @slow --invert'
     | 							                                 ^
  71 | 						}
  72 | 						return './node_modules/.bin/_mocha --bail test/integration/index.js ' + slowTag;
  73 | 					} else {


2 errors found.
1 error potentially fixable with the `--fix` option.
```

**Comment by karmacoma** [comment]
If possible, we should probably reverse targets to include **everything**, and then exclude selected files, directories.
