### ISSUE TITLE
Common block validation fails when no common block found

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1273]
During synchronisation process, when no common block is found with randomly selected peer, common block validation fails (https://github.com/LiskHQ/lisk/blob/development/modules/blocks/process.js#L245).

The `library.schema.validate` expects string or json to validate, but receives null instead.

```
[inf] 2018-01-11 12:51:21 | Looking for common block with: 127.0.0.1:5001
[FTL] 2018-01-11 12:51:21 | System error - {"message":"Cannot read property 'length' of null","stack":"TypeError: Cannot read property 'length' of null\n    at ZSchema.id (/Users/macio/projects/liskHQ/lisk-copy-22/helpers/z_schema.js:33:10)\n    at ZSchema.format (/Users/macio/projects/liskHQ/lisk-copy-22/node_modules/z-schema/src/JsonValidation.js:336:39)\n    at ZSchema.exports.validate (/Users/macio/projects/liskHQ/lisk-copy-22/node_modules/z-schema/src/JsonValidation.js:516:39)\n    at ZSchema.recurseObject (/Users/macio/projects/liskHQ/lisk-copy-22/node_modules/z-schema/src/JsonValidation.js:440:30)\n    at ZSchema.exports.validate (/Users/macio/projects/liskHQ/lisk-copy-22/node_modules/z-schema/src/JsonValidation.js:525:27)\n    at ZSchema.validate (/Users/macio/projects/liskHQ/lisk-copy-22/node_modules/z-schema/src/ZSchema.js:203:33)\n    at async.waterfall.library.db.blocks.getCommonBlock.id (/Users/macio/projects/liskHQ/lisk-copy-22/modules/blocks/process.js:9:8447)\n    at nextTask (/Users/macio/projects/liskHQ/lisk-copy-22/node_modules/async/dist/async.js:5273:14)\n    at Immediate.next (/Users/macio/projects/liskHQ/lisk-copy-22/node_modules/async/dist/async.js:5280:9)\n    at Immediate.<anonymous> (/Users/macio/projects/liskHQ/lisk-copy-22/node_modules/async/dist/async.js:906:16)\n    at runCallback (timers.js:670:20)\n    at tryOnImmediate (timers.js:639:5)\n    at processImmediate [as _immediateCallback] (timers.js:611:5)"}
[inf] 2018-01-11 12:51:21 | Cleaning up...
```

**Comment by karmacoma** [comment]
Closed by PR: https://github.com/LiskHQ/lisk/pull/1400
