### ISSUE TITLE
Integration tests are failing when given configurations for 10 nodes with address "127.0.0.1"

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1475]
### Expected behavior

No failing tests.

### Actual behavior

```
5 passing (1m)
  1 failing

  1) given configurations for 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases
       when every peers contains the others on the peers list
         when every peer forges with separate subset of genesis delegates and forging.force = false
           when network is set up
             when WS connections to all nodes all established
               when functional tests are successfully executed against 127.0.0.1:5000
                 "before all" hook:
     Error: done() invoked with non-Error: Functional tests failed
      at ChildProcess.child.on.code (test/integration/setup/shell.js:65:12)
      at maybeClose (internal/child_process.js:920:16)
      at Socket.<anonymous> (internal/child_process.js:351:11)
      at Pipe._handle.close [as _onclose] (net.js:497:12)
```

### Steps to reproduce

```
npm run test mocha:untagged:integration
```

### Which version(s) does this affect? (Environment, OS, etc...)

`1.0.0`

**Comment by MaciejBaj** [comment]
The tests are failing because of nodes experiencing the error during looking for a common block while syncing. Seems like #1273 is still not solved.
The error gathered from a server running during integration tests:
```
[inf] 2018-01-30 12:53:21 | Looking for common block with: 127.0.0.1:5009
[ERR] 2018-01-30 12:53:21 | Expected type string but found type null
[ERR] 2018-01-30 12:53:21 | Failed to find common block with: 127.0.0.1:5009
```

**Comment by ManuGowda** [comment]
@MaciejBaj I am reopening this issue as the integration tests are failing at times and passing few times, so its behaving bit inconsistent, here is the observation from the build fail
```
Running "exec:mocha:untagged:integration" (exec) task


  given configurations for 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases
    when every peers contains the others on the peers list
      when every peer forges with separate subset of genesis delegates and forging.force = false
        when network is set up
[log] 2018-02-07 15:42:35 | Generating PM2 configuration
[log] 2018-02-07 15:42:35 | Recreating databases
[log] 2018-02-07 15:42:36 | Clearing existing logs
[log] 2018-02-07 15:42:36 | Launching network
[log] 2018-02-07 15:42:38 | Waiting for nodes to load the blockchain
[log] 2018-02-07 15:43:03 | Enabling forging with registered delegates
[log] 2018-02-07 15:43:03 | Waiting 20 seconds for nodes to establish connections
          when WS connections to all nodes all established
            Peers
              mutual connections
                1) should return a list of peers mutually interconnected
>> Test failed: should return a list of peers mutually interconnected
PM2 process killed gracefully
          2) "after all" hook

  0 passing (49s)
  2 failing

  1) given configurations for 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases
       when every peers contains the others on the peers list
         when every peer forges with separate subset of genesis delegates and forging.force = false
           when network is set up
             when WS connections to all nodes all established
               Peers
                 mutual connections
                   should return a list of peers mutually interconnected:
     AssertionError: expected [] not to be empty
      at results.forEach.result (test/integration/scenarios/network/peers.js:40:18)
```

**Comment by ManuGowda** [comment]
Closing this issue as db index logic no more uses `require-all` module and the build is passing successfully.
