### ISSUE TITLE
Add unit test coverage for db/repos/rounds

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1592]
Parent: #1484

### Expected behavior
We need 100% coverage for db/repos/rounds

### Actual behavior
Currently there is no coverage for this repo.

**Comment by diego-G** [comment]
I've just notice an error on this new test file:
```
        1) should return unique round numbers

 1) db
       RoundsRepository
         getMemRounds()
           should return unique round numbers:

      AssertionError: expected [ '2', '1' ] to deeply equal [ '1', '2' ]
      + expected - actual

       [
      +  "1"
         "2"
      -  "1"
       ]
      
    at Context.<anonymous> (test/unit/db/repos/rounds.js:105:52)
    at undefined.next (native)
    at onFulfilled (node_modules/co/index.js:65:19)
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

```

**Comment by nazarhussain** [comment]
@diego-G Its passing correctly on my machine and on jenkins perfectly fine. I am running: 

> PostgreSQL 9.6.6 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit

Its related PostgreSQL running on your machine, which is ordering the records differently than running on mine or jenkins server.

**Comment by nazarhussain** [comment]
@diego-G Since the order or round number is not important so skipped the strict order checking in the test. But I suggest to always run PostgreSQL or any database server on a linux environment.
