### ISSUE TITLE
Error loading transport modules on application restart

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#1830]
### Expected behavior
Application should start properly each time it restarts. 
### Actual behavior
Application logs following error on restarts sometimes:

```
2018-04-09 09:45:10 529: [FTL] 2018-04-09 09:45:10 | Domain master - {"message":"Cannot read property 'peers' of undefined","stack":"TypeError: Cannot read property 'peers' of undefined\n    at Object.list (/home/lisk/lisk-1.0.0-beta.2-Linux-x86_64/modules/transport.js:615:13)\n    at MasterWAMPServer.processWAMPRequest (/home/lisk/lisk-1.0.0-beta.2-Linux-x86_64/node_modules/wamp-socket-cluster/WAMPServer.js:58:48)\n    at EventEmitter.MasterWAMPServer.socketCluster.on (/home/lisk/lisk-1.0.0-beta.2-Linux-x86_64/node_modules/wamp-socket-cluster/MasterWAMPServer.js:23:10)\n    at emitThree (events.js:116:13)\n    at EventEmitter.emit (events.js:194:7)\n    at ChildProcess.workerHandler (/home/lisk/lisk-1.0.0-beta.2-Linux-x86_64/node_modules/socketcluster/index.js:706:12)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at process.nextTick (internal/child_process.js:787:12)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"}
```
### Steps to reproduce

```
/bin/bash lisk.sh reload
```

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by nazarhussain** [comment]
That seems related to issue #1839. When we restart instance all our modules are re-initiated. While control does not reach to point yet 

https://github.com/LiskHQ/lisk/blob/bbe4803ff88627fd76cec9628635e48acd2db6c8/modules/transport.js#L306-L308

Some other node who have already an address of that instance make a WS request. And it crashes at point:

https://github.com/LiskHQ/lisk/blob/bbe4803ff88627fd76cec9628635e48acd2db6c8/modules/transport.js#L611-L615


So probably we should start accepting WS requests after DB and all other modules are ready and bonded properly in app.js
