### ISSUE TITLE
Strange logs related to P2P on node - (Needs investigation)

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#1831]
### Expected behavior
If node disconnects with the a peer, it should only log once that it has disconnected/exited. But the logs are displayed multiple times, which could mean that there is a possible memory leak or there are multiple socket connections to the same peer.
### Actual behavior
Logs are displayed repeatedly, and then node gets the error:
```
2018-04-06 23:43:17 158: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 37.139.29.38 failed with code 4001 and reason -
2018-04-06 23:43:17 158: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 167.99.251.165 failed with code 4001 and reason -
2018-04-06 23:43:17 159: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 167.99.165.231 failed with code 4001 and reason -
2018-04-06 23:43:17 160: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 206.189.48.87 failed with code 4001 and reason -
2018-04-06 23:43:17 160: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 94.237.41.95 failed with code 4001 and reason -
2018-04-06 23:43:17 161: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 94.237.41.95 failed with code 4001 and reason -
2018-04-06 23:43:17 162: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 94.237.41.95 failed with code 4001 and reason -
2018-04-06 23:43:17 162: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 94.237.41.95 failed with code 4001 and reason -
2018-04-06 23:43:17 163: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 94.237.41.95 failed with code 4001 and reason -
2018-04-06 23:43:17 164: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 167.99.165.232 failed with code 4001 and reason -
2018-04-06 23:43:17 164: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 167.99.165.231 failed with code 4001 and reason -
2018-04-06 23:43:17 165: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 167.99.165.231 failed with code 4001 and reason -
2018-04-06 23:43:17 166: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 185.14.187.61 failed with code 4001 and reason -
2018-04-06 23:43:17 166: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 104.236.61.243 failed with code 4001 and reason -
2018-04-06 23:43:17 167: [dbg] 2018-04-06 23:43:17 | [Outbound socket :: close] Peer connection to 167.99.165.232 failed with code 4001 and reason -
2018-04-06 23:43:17 234: [FTL] 2018-04-06 23:43:17 | Domain master - {"message":"spawn ENOMEM","stack":"Error: spawn ENOMEM\n    at exports._errnoException (util.js:1020:11)\n    at ChildProcess.spawn (internal/child_process.js:328:11)\n    at exports.spawn (child_process.js:370:9)\n    at exports.fork (child_process.js:59:10)\n    at EventEmitter.SocketCluster._launchWorkerCluster (/home/lisk/lisk-1.0.0-beta.2-Linux-x86_64/node_modules/socketcluster/index.js:682:24)\n    at EventEmitter.SocketCluster._handleWorkerClusterExit (/home/lisk/lisk-1.0.0-beta.2-Linux-x86_64/node_modules/socketcluster/index.js:614:8)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)"}
2018-04-06 23:43:17 272: [inf] 2018-04-06 23:43:17 | Cleaning up...
```
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by pcdinh** [comment]
Is it possibly related to this issue? https://github.com/LiskHQ/lisk/issues/1836

**Comment by MaciejBaj** [comment]
You are right @pcdinh, there is an unexpected memory consumption while client WS sockets are not being destroyed in the correct way. The PR closing #1836 solves it.

**Comment by jondubois** [comment]
Yes @pcdinh @MaciejBaj I think it was the same issue and it has been fixed https://github.com/LiskHQ/lisk/pull/1837.
