### ISSUE TITLE
undefined is not a function in app.js<-async.js<-timers.js

### ISSUE THREAD

**Issue by ByronAP** [LiskHQ/lisk#184]
System error { message: 'undefined is not a function',
  stack: 'TypeError: undefined is not a function\n    at /home/lisk/lisk-main/app.js:3:9842\n    at /home/lisk/lisk-main/node_modules/async/lib/async.js:52:16\n    at Immediate.<anonymous> (/home/lisk/lisk-main/node_modules/async/lib/async.js:264:21)\n    at Immediate.<anonymous> (/home/lisk/lisk-main/node_modules/async/lib/async.js:44:16)\n    at Immediate.immediate._onImmediate (timers.js:418:16)\n    at processImmediate [as _immediateCallback] (timers.js:367:17)' }
info 2016-06-10 11:35:29 Cleaning up...
info 2016-06-10 11:35:29 Cleaned up successfully
error 2016-06-10 11:35:29 null
error: Forever detected script exited with code: 1

may be related to #28

**Comment by ByronAP** [comment]
please merge into #180
