### ISSUE TITLE
Socket that requested RPC call not found anymore

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk#1855]
### Expected behavior

This error should not be thrown.

### Actual behavior

After adding more logging https://github.com/LiskHQ/lisk/pull/1854, the following error was uncovered:

```sh
[ERR] 2018-04-10 16:38:01 | Error: Socket that requested RPC call not found anymore
    at EventEmitter.SlaveWAMPServer.worker.on (/home/lisk/lisk-1.0.0-beta.3-Linux-x86_64/node_modules/wamp-socket-cluster/SlaveWAMPServer.js:37:12)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.SCWorker.handleMasterMessage (/home/lisk/lisk-1.0.0-beta.3-Linux-x86_64/node_modules/socketcluster/scworker.js:489:8)
    at process.handleWorkerClusterMessage (/home/lisk/lisk-1.0.0-beta.3-Linux-x86_64/node_modules/socketcluster/scworker.js:527:16)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

This error crashes the worker process.
Note that this is a different error from #1856 - Which also causes the worker process to crash.

### Steps to reproduce

You need to run a node on beta-net to reproduce.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0; latest beta net.

**Comment by jondubois** [comment]
This is probably a side effect of fixing this issue https://github.com/LiskHQ/lisk/issues/1836 - Since we are now deleting the socket object.
