### ISSUE TITLE
Cannot read property 'peers' of undefined crashing master process

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk#1865]
### Expected behavior

This error should not happen.

### Actual behavior

```sh
[FTL] 2018-04-11 13:54:48 | Domain master - {"message":"Cannot read property 'peers' of undefined","stack":"TypeError: Cannot read property 'peers' of undefined
    at Object.list (/home/lisk/lisk-1.0.0-beta.3-Linux-x86_64/modules/transport.js:615:13)
    at MasterWAMPServer.processWAMPRequest (/home/lisk/lisk-1.0.0-beta.3-Linux-x86_64/node_modules/wamp-socket-cluster/WAMPServer.js:58:48)
    at EventEmitter.MasterWAMPServer.socketCluster.on (/home/lisk/lisk-1.0.0-beta.3-Linux-x86_64/node_modules/wamp-socket-cluster/MasterWAMPServer.js:23:10)
    at emitThree (events.js:116:13)\n    at EventEmitter.emit (events.js:194:7)
    at ChildProcess.workerHandler (/home/lisk/lisk-1.0.0-beta.3-Linux-x86_64/node_modules/socketcluster/index.js:706:12)\n    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)\n    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"}

```

This error crashes the master process.

### Steps to reproduce

Run the node remotely on beta-net and let node connect to peers, this error happens sometimes.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0, latest beta-net.

**Comment by jondubois** [comment]
Closing since this is a duplicate of https://github.com/LiskHQ/lisk/issues/1830
