### ISSUE TITLE
Client connection establishment timed out causing a fatal error which crashes worker

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk#1875]
### Expected behavior

This error should not be fatal.

### Actual behavior

```sh
[FTL] 2018-04-13 18:49:55 | System error - {"message":"Client connection establishment timed out","stack":"SocketProtocolError: Client connection establishment timed out\n    at Emitter.SCSocket._onSCClose (/Users/jondubois/projects/lisk/lisk/node_modules/socketcluster-client/lib/scsocket.js:640:15)\n    at Emitter.<anonymous> (/Users/jondubois/projects/lisk/lisk/node_modules/socketcluster-client/lib/scsocket.js:289:12)\n    at Emitter.emit (/Users/jondubois/projects/lisk/lisk/node_modules/component-emitter/index.js:133:20)\n    at Emitter.SCTransport._onClose (/Users/jondubois/projects/lisk/lisk/node_modules/socketcluster-client/lib/sctransport.js:215:28)\n    at Timeout.<anonymous> (/Users/jondubois/projects/lisk/lisk/node_modules/socketcluster-client/lib/sctransport.js:122:10)\n    at ontimeout (timers.js:386:11)\n    at tryOnTimeout (timers.js:250:5)\n    at Timer.listOnTimeout (timers.js:214:5)"}
```

It doesn't happen very often, but when it does, it crashes the worker process.

Last time it happened, I also got this error immediately after:

```
[ERR] 2018-04-13 18:49:55 | Discovering new peers failed - RPC response timeout exceeded
```

### Steps to reproduce

Launch a node (reproduced on localhost, connecting to latest beta net).

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0 - Latest beta net.

**Comment by jondubois** [comment]
This issue has been resolved in a previous PR. Note that this issue was not about the connection timing out (this can happen for a number of reasons; it was about the fact that connection timeout was throwing a fatal error and crashing the worker process.
