### ISSUE TITLE
Functional http get tests fail randomly

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#2015]
### Expected behavior
Tests should be stable.
### Actual behavior
Tests are unstable and fail randomly.
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by 4miners** [comment]
Reference, https://jenkins.lisk.io/job/lisk-core/job/1994_secret-rename/2/execution/node/202/log/:
```
16:57:52 [0m  1) GET /delegates
16:57:52        /
16:57:52          secondPublicKey
16:57:52            "before all" hook:
16:57:52 [0m[31m     Error: Exceeded limit to wait for confirmations[0m[90m
16:57:52       at waitUntilLimit (test/common/utils/wait_for.js:191:10)
16:57:52       at blocksPromise.then.catch (test/common/utils/wait_for.js:200:12)
16:57:52       at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
16:57:52       at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
16:57:52       at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
16:57:52       at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
16:57:52       at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
16:57:52       at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
16:57:52       at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
16:57:52       at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
16:57:52 [0m
16:57:52 
16:57:52 
16:57:52 Test failed: test/functional/http/get/delegates.js
16:57:52 >> Exited with code: 1.
16:57:52 >> Error executing child process: Error: Process exited with code 1.
16:57:52 Warning: Task "exec:mocha:untagged:functional:get" failed. Use --force to continue.
```
