### ISSUE TITLE
Various tests fails randomly

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#2277]
### Expected behavior
Tests should always pass of fail in consistent way.
### Actual behavior
Tests are failing randomly:
- [ ] test/functional/system/blocks/verify/verify.js
- [ ] test/unit/logic/vote.js
### Steps to reproduce
Run tests.
### Which version(s) does this affect? (Environment, OS, etc...)
1.2.0

**Comment by 4miners** [comment]
```
16:00:22 >> AssertionError: expected 'Failed to add vote, delegate "genesis_99" already voted for' to equal 'Failed to add vote, delegate "genesis_95" already voted for'
16:00:22 >>   at Immediate.vote.checkConfirmedDelegates.err (/home/lisk/workspace/lisk-core_PR-2260-PV423FBMEW4557B5BHOHFO346ZBWSDWAOXDYECYG5EEIEQWM2PVQ/test/unit/logic/vote.js:410:20)
16:00:22 >>   at runCallback (timers.js:674:20)
16:00:22 >>   at tryOnImmediate (timers.js:645:5)
16:00:22 >>   at processImmediate [as _immediateCallback] (timers.js:617:5)
16:00:22 Test failed: test/unit/logic/vote.js
16:00:22 >> Exited with code: 7.
16:00:22 >> Error executing child process: Error: Process exited with code 7.
16:00:22 Warning: Task "exec:mocha:default:unit" failed. Use --force to continue.
```
Reference: https://jenkins.lisk.io/job/lisk-core/view/change-requests/job/PR-2260/5/execution/node/205/log/

```
14:49:34 >> AssertionError: expected 'Failed to add vote, delegate "genesis_99" already voted for' to equal 'Failed to add vote, delegate "genesis_95" already voted for'
14:49:34 >>   at Immediate.vote.checkConfirmedDelegates.err (/home/lisk/workspace/lisk-core_PR-2260-PV423FBMEW4557B5BHOHFO346ZBWSDWAOXDYECYG5EEIEQWM2PVQ/test/unit/logic/vote.js:410:20)
14:49:34 >>   at runCallback (timers.js:674:20)
14:49:34 >>   at tryOnImmediate (timers.js:645:5)
14:49:34 >>   at processImmediate [as _immediateCallback] (timers.js:617:5)
14:49:34 
14:49:34 
14:49:34 [92m [0m[32m 13 passing[0m[90m (42s)[0m
14:49:34 [36m [0m[36m 1 pending[0m
14:49:34 
14:49:34 Test failed: test/unit/logic/vote.js
14:49:34 >> Exited with code: 7.
14:49:34 >> Error executing child process: Error: Process exited with code 7.
14:49:34 Warning: Task "exec:mocha:default:unit" failed. Use --force to continue.
```
https://jenkins.lisk.io/job/lisk-core/view/change-requests/job/PR-2260/3/execution/node/205/log/

**Comment by 4miners** [comment]
Closing that as issues detected are already fixed as part of 1.1.0 release. 😕

**Comment by ManuGowda** [comment]
Reopening this issue as the `1.2.0` Jenkins build failed multiple times, cache, API blocks and expire multi-signature transactions were the common cause of this, so its good revisit them until they consistently succeed.

**Comment by diego-G** [comment]
Another related to cache https://jenkins.lisk.io/job/lisk-core/view/change-requests/job/PR-2521/2/console

**Comment by pablitovicente** [comment]
```+ set -o pipefail

+ '[' params.JENKINS_PROFILE == jenkins-extensive ']'

+ npm test -- mocha:default:network

+ tee networkTests.logs



> lisk@1.4.0-alpha.0 test /home/lisk/workspace/lisk-core-network_PR-2597

> grunt "mocha:default:network"



Running "mocha:default:network" (mocha) task



Running "exec:mocha:default:network" (exec) task





  Start a network of 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases

[log] 2018-12-05 16:52:58 | Generating PM2 configuration

[log] 2018-12-05 16:52:58 | Recreating databases

[log] 2018-12-05 16:52:59 | Clearing existing logs

[log] 2018-12-05 16:52:59 | Launching network

[log] 2018-12-05 16:53:02 | Waiting for all nodes to load the blockchain

[log] 2018-12-05 16:53:02 | Waiting for nodes node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9 to load the blockchain

[log] 2018-12-05 16:53:11 | Enabling forging with registered delegates

[log] 2018-12-05 16:53:11 | Waiting for blocks on all nodes

[log] 2018-12-05 16:53:11 | Waiting for blocks on nodes node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9

[log] 2018-12-05 16:53:14 | Waiting 20 seconds for nodes to establish connections

    ✓ there should be exactly 10 listening connections for 500[0-9] ports (376ms)

    ✓ there should be a maximum 180 established connections from 500[0-9] ports (379ms)

    when WS connections to all nodes all established

      @network : peer Disconnect

[log] 2018-12-05 16:53:34 | Waiting for all nodes to load the blockchain

[log] 2018-12-05 16:53:34 | Waiting for nodes node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9 to load the blockchain

        when peers are mutually connected in the network

          when a node is stopped

            ✓ peer manager should remove peer from the list and there should be 144 established connections from 500[0-9] ports (375ms)

          when a stopped node is started

            ✓ there should be 180 established connections from 500[0-9] ports (339ms)

          node restart

Wait for nodes to be started

[log] 2018-12-05 16:53:48 | Enabling forging with registered delegates

[log] 2018-12-05 16:53:48 | Waiting for blocks on all nodes

[log] 2018-12-05 16:53:48 | Waiting for blocks on nodes node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9

            after all the nodes restart

              ✓ there should be 198 established connections from 500[0-9] ports (400ms)

      @network : peers

[log] 2018-12-05 16:53:50 | Waiting for all nodes to load the blockchain

[log] 2018-12-05 16:53:50 | Waiting for nodes node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9 to load the blockchain

        mutual connections

          ✓ should return a list of peers mutually interconnected

          ✓ should have all the required peer properties

        forging

[log] 2018-12-05 16:53:51 | Waiting for blocks on all nodes

[log] 2018-12-05 16:53:51 | Waiting for blocks on nodes node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9

          network status after 3 blocks

            ✓ should have no error

            ✓ should have height > 1

            ✓ should have average height above 1

            ✓ should have valid values matching specification

            ✓ should have different peers heights propagated correctly on peers lists

            ✓ should have matching height across all nodes

      @network : peer Blacklisted

[log] 2018-12-05 16:54:27 | Waiting for all nodes to load the blockchain

[log] 2018-12-05 16:54:27 | Waiting for nodes node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9 to load the blockchain

        when peers are mutually connected in the network

          ✓ there should be 180 established connections from 500[0-9] ports (360ms)

          when a node blacklists an ip

            ✓ there should be 144 established connections from 500[0-9] ports (394ms)

            ✓ peers manager should contain 8 active connections

            ✓ node_0 should have every peer banned

            ✓ node_1 should have only himself and node_0 disconnected (80ms)

          when a node remove the just blacklisted ip

            1) there should be 180 established connections from 500[0-9] ports

>> Test failed: there should be 180 established connections from 500[0-9] ports

            2) "after each" hook for "there should be 180 established connections from 500[0-9] ports"

[log] 2018-12-05 16:54:38 | Shutting down network

PM2 process killed gracefully





  18 passing (2m)

  2 failing



  1) Start a network of 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases

       when WS connections to all nodes all established

         @network : peer Blacklisted

           when peers are mutually connected in the network

             when a node remove the just blacklisted ip

               there should be 180 established connections from 500[0-9] ports:

     Error: done() invoked with non-Error: There are 198 established connections on web socket ports.

      at utils.getEstablishedConnections (test/network/scenarios/p2p/peers_blacklist.js:187:15)

      at childProcess.exec (test/network/utils/index.js:48:5)

      at ChildProcess.exithandler (child_process.js:268:7)

      at maybeClose (internal/child_process.js:915:16)

      at Socket.stream.socket.on (internal/child_process.js:336:11)

      at Pipe._handle.close [as _onclose] (net.js:561:12)



  2) Start a network of 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases

       "after each" hook for "there should be 180 established connections from 500[0-9] ports":

     Error: done() invoked with non-Error: There are 198 established connections on web socket ports.

      at utils.getEstablishedConnections (test/network/scenarios/p2p/peers_blacklist.js:187:15)

      at childProcess.exec (test/network/utils/index.js:48:5)

      at ChildProcess.exithandler (child_process.js:268:7)

      at maybeClose (internal/child_process.js:915:16)

      at Socket.stream.socket.on (internal/child_process.js:336:11)

      at Pipe._handle.close [as _onclose] (net.js:561:12)







>> Exited with code: 2.

>> Error executing child process: Error: Process exited with code 2.

Warning: Task "exec:mocha:default:network" failed. Use --force to continue.



Aborted due to warnings.

npm ERR! Test failed.  See above for more details.

script returned exit code 1
```


Reference: https://jenkins.lisk.io/blue/rest/organizations/jenkins/pipelines/lisk-core-network/branches/PR-2597/runs/5/nodes/32/log/?start=0

**Comment by shuse2** [comment]
superseded by #3096
