### ISSUE TITLE
peers.remove called with wrong parameters on Node start

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#2406]
### Problem description
When Node starts, transactions are being loaded from a network: 
https://github.com/LiskHQ/lisk/blob/development/modules/loader.js#L254

When invalid transactions are present in a network and Node returns them:
https://github.com/LiskHQ/lisk/blob/development/modules/loader.js#L269

the validation fails and Peer that returned it is being removed:
https://github.com/LiskHQ/lisk/blob/development/modules/loader.js#L308

The call passes wrong parameters to `modules.peers.remove` function - a string instead of Peer object, which results in a Node crash with the following error message:
``
[WRN] 2018-09-16 01:26:28 | Transaction  is not valid, peer removed - 94.237.40.141:8001
``
``
[FTL] 2018-09-16 01:26:28 | System error - {"message":"Cannot create property 'wsPort' on string '94.237.40.141'","stack":"TypeError: Cannot create property 'wsPort' on string '94.237.40.141'\n    at Peer.normalize (/home/lisk/lisk-main/logic/peer.js:80:15)\n    at Peer.accept (/home/lisk/lisk-main/logic/peer.js:47:15)\n    at new Peer (/home/lisk/lisk-main/logic/peer.js:35:15)\n    at Peers.create (/home/lisk/lisk-main/logic/peers.js:81:10)\n    at Peers.remove (/home/lisk/lisk-main/logic/peers.js:285:14)\n    at Peers.remove (/home/lisk/lisk-main/modules/peers.js:512:29)\n    at async.eachSeries.e (/home/lisk/lisk-main/modules/loader.js:309:22)\n    at /home/lisk/lisk-main/node_modules/async/dist/async.js:3060:16\n    at replenish (/home/lisk/lisk-main/node_modules/async/dist/async.js:946:17)\n    at Immediate.iterateeCallback (/home/lisk/lisk-main/node_modules/async/dist/async.js:931:17)\n    at Immediate.<anonymous> (/home/lisk/lisk-main/node_modules/async/dist/async.js:906:16)\n    at Immediate.args.(anonymous function) (/home/lisk/lisk-main/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"}
``
### How to fix it?
Attempt to [remove Peer in the loader](https://github.com/LiskHQ/lisk/blob/development/modules/loader.js#L308) should pass a full Peer object as a parameter - `modules.peers.remove(peer);`

### Which version(s) does this affect? (Environment, OS, etc...)
`>=1.0.0`

**Comment by MaciejBaj** [comment]
Closed by https://github.com/LiskHQ/lisk/commit/b796c7df2903fe86e489212cdb3152febf673be0
