### ISSUE TITLE
"Cannot read property 'network' of undefined"

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#273]
I often reset my private testnet database using "dropdb" to have a defined environmant.
The first start of the lisk client after resetting the database stops with the following error:

```
$ node app.js 
[inf] 2016-09-11 12:08:44 | Lisk started: 0.0.0.0:7000
NOTICE:  view "blocks_list" does not exist, skipping
NOTICE:  view "full_blocks_list" does not exist, skipping
NOTICE:  view "trs_list" does not exist, skipping
NOTICE:  trigger "protect_mem_accounts" for relation "mem_accounts" does not exist, skipping
NOTICE:  function revert_mem_account() does not exist, skipping
[FTL] 2016-09-11 12:08:47 | System error - {"message":"Cannot read property 'network' of undefined","stack":"TypeError: Cannot read property 'network' of undefined\n    at Transaction.DApp.afterSave (/home/jens/src/coins/lisk/lisk/logic/dapp.js:331:10)\n    at Transaction.afterSave (/home/jens/src/coins/lisk/lisk/logic/transaction.js:705:29)\n    at /home/jens/src/coins/lisk/lisk/modules/blocks.js:327:36\n    at /home/jens/src/coins/lisk/lisk/node_modules/async/lib/async.js:181:20\n    at Immediate.iterate [as _onImmediate] (/home/jens/src/coins/lisk/lisk/node_modules/async/lib/async.js:262:13)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)"}
```

The next start will be successful.

**Comment by TheGoldenEye** [comment]
The error occurs here:
https://github.com/LiskHQ/lisk/blob/development/logic/dapp.js#L331
The variable "library" is not yet initialized

**Comment by karmacoma** [comment]
@TheGoldenEye Ok thanks, we will resolve asap.
