### ISSUE TITLE
Dapp crashed on forging node while other node accessed blocks

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#29]
Let's say we have nodes
A - Forging node Dapp
B - fresh node which have installed dapp.

While node B 

```
dapp loading process pid 24280

Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js:

dapp loaded process pid 24280

Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js:

blocks 1
current 0

Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js:

blockchain loaded

log 2016-04-03 09:12:40 Recieved new block id: 10459133828029609000 height: 430524 slot: 3115156 reward: 500000000
Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js:

loop skip slot

Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js:

found blocks at 89.69.168.15:7000

info 2016-04-03 09:12:40 Removing peer POST http://194.151.78.72:7000/peer/blocks
warn 2016-04-03 09:12:40 Main queue 70
warn 2016-04-03 09:12:40 Main queue 69
warn 2016-04-03 09:12:40 Main queue 68
warn 2016-04-03 09:12:40 Main queue 67
warn 2016-04-03 09:12:40 Main queue 66
warn 2016-04-03 09:12:40 Main queue 65
warn 2016-04-03 09:12:40 Main queue 64
warn 2016-04-03 09:12:40 Main queue 64
warn 2016-04-03 09:12:40 Main queue 64
warn 2016-04-03 09:12:40 Main queue 63
warn 2016-04-03 09:12:40 Main queue 62
warn 2016-04-03 09:12:40 Main queue 61
warn 2016-04-03 09:12:41 Main queue 60
warn 2016-04-03 09:12:41 Main queue 59
warn 2016-04-03 09:12:41 Main queue 58
warn 2016-04-03 09:12:41 Main queue 57
warn 2016-04-03 09:12:41 Main queue 56
warn 2016-04-03 09:12:41 Main queue 55
warn 2016-04-03 09:12:41 Main queue 54
warn 2016-04-03 09:12:41 Main queue 53
warn 2016-04-03 09:12:41 Main queue 52
warn 2016-04-03 09:12:41 Main queue 51
warn 2016-04-03 09:12:41 Main queue 50
Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js:

load blocks after 1

info 2016-04-03 09:12:41 Check blockchain on 104.238.167.95:7000
info 2016-04-03 09:12:44 Removing peer POST http://87.106.127.28:7000/peer/blocks
error 2016-04-03 09:12:44 loadUnconfirmedTransactions timer Transaction already exists
Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js:

blockSync timer { code: 'ETIMEDOUT', connect: false }
```

Node A dapp crashed
<a title="http://pastebin.com/Y2SSAEhM" href="http://pastebin.com/Y2SSAEhM">http://pastebin.com/Y2SSAEhM</a>

Seems that fetched blockchain has json formatting issue at block 104
`"b_height": 104 % 2 C "b_payloadLength"`

hope it's enough informations

```
SyntaxError: Unexpected token %
    at Sandbox._parse (/root/lisk-0.1.2-Linux-x86_64/node_modules/lisk-sandbox/index.js:42:24)
    at Sandbox.<anonymous> (/root/lisk-0.1.2-Linux-x86_64/node_modules/lisk-sandbox/index.js:193:9)
    at Array.forEach (native)
    at Sandbox._listen (/root/lisk-0.1.2-Linux-x86_64/node_modules/lisk-sandbox/index.js:192:9)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:540:20)
```

**Comment by karek314** [comment]
Actually i was able to reproduce issue, after recreating blockchain from genesis block, Issue occurred now at height:151
```
"t_t_transactionId": "",
"gb_entry" % 3 A "",
"gb_transactionId": ""
```

**Comment by fix** [comment]
Is this still happening with new versions 0.2.2+ ?

**Comment by karek314** [comment]
I will check as soon as possible and let you know

**Comment by fix** [comment]
is this still occuring with 0.3.2?

**Comment by karmacoma** [comment]
Closing due to: https://github.com/LiskHQ/lisk/issues/560
