### ISSUE TITLE
guestBook Example crashed while submitting new entry

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#30]
```
new dapp block id: 11676784247852398241 height: 134 via point: 430941

Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js: 

transactionsSync timer No peers in db

info 2016-04-03 16:27:57 Check blockchain on 104.156.254.116:7000 
Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js: 

transactionsSync timer No peers in db

log 2016-04-03 16:28:00 Recieved new block id: 1330181692556271794 height: 430942 slot: 3115608 reward: 500000000 
info 2016-04-03 16:28:00 Removing peer POST http://194.151.78.72:7000/peer/blocks 
info 2016-04-03 16:28:00 Removing peer POST http://194.151.78.72:7000/peer/transactions 
info 2016-04-03 16:28:01 Removing peer POST http://91.246.70.118:7000/peer/transactions 
info 2016-04-03 16:28:01 Removing peer POST http://87.106.127.28:7000/peer/transactions 
info 2016-04-03 16:28:01 Removing peer POST http://109.153.180.57:7000/peer/transactions 
Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js: 

Error: Error: near line 220477: UNIQUE constraint failed: dapp_8565618818751641866_transactions.id


Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:297:12)
    at /root/lisk-0.1.2-Linux-x86_64/node_modules/lisk-sandbox/index.js:113:24
    at /root/lisk-0.1.2-Linux-x86_64/node_modules/async/lib/async.js:987:13
    at Immediate.q.process [as _onImmediate] (/root/lisk-0.1.2-Linux-x86_64/node_modules/async/lib/async.js:953:21)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
info 2016-04-03 16:28:08 Dapp 8565618818751641866 closed  
info 2016-04-03 16:28:08 Encountered error in dapp 8565618818751641866 Error: This socket has been ended by the other party 
info 2016-04-03 16:28:08 Dapp 8565618818751641866 closed  
```

**Comment by karmacoma** [comment]
Closing issue here. Moving to guestBook repository: https://github.com/MaxKK/guestbookDapp/issues/1
