### ISSUE TITLE
[ERR] Failed to sweep peers - Error: ERROR:  deadlock detected

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk#323]
**Testnet v0.5.0f**
My node got some fork 1. I waited 5-10 minutes to let it recover by itself but it seemed like it couldn't recover. Then I did a manual `reload`. After the `reload` the log showed:

```
[inf] 2016-11-28 14:35:20 | Received new block id: 5167919988021745732 height: 979110 round: 9695 slot: 1623452 reward: 500000000
[inf] 2016-11-28 14:35:21 | Broadhash consensus updated to 4 %
[WRN] 2016-11-28 14:35:22 | ERESPONSE 500 Removing peer 188.68.55.185:7000 POST http://188.68.55.185:7000/peer/blocks
[WRN] 2016-11-28 14:35:22 | EUNAVAILABLE Removing peer 208.110.70.106:7000 POST http://208.110.70.106:7000/peer/blocks
[WRN] 2016-11-28 14:35:23 | EUNAVAILABLE Removing peer 159.203.133.123:7000 POST http://159.203.133.123:7000/peer/blocks
[WRN] 2016-11-28 14:35:29 | ETIMEOUT Ban 149.56.140.162:7000 10 minutes GET http://149.56.140.162:7000/peer/height
[ERR] 2016-11-28 14:35:29 | Failed to get height from peer: 149.56.140.162:7000
[inf] 2016-11-28 14:35:40 | Received new block id: 5371390954258055292 height: 979111 round: 9695 slot: 1623454 reward: 500000000
[inf] 2016-11-28 14:35:42 | Broadhash consensus updated to 23 %
[WRN] 2016-11-28 14:35:43 | EUNAVAILABLE Removing peer 208.110.70.106:7000 POST http://208.110.70.106:7000/peer/blocks
```

and then suddenly this showed up:

```
[ERR] 2016-11-28 14:35:43 | Failed to sweep peers - Error: ERROR:  deadlock detected
DETAIL:  Process 3987 waits for ShareLock on transaction 1770130; blocked by process 4019.
Process 4019 waits for ShareLock on transaction 1770126; blocked by process 3987.
HINT:  See server log for query details.
CONTEXT:  while inserting index tuple (6,54) in relation "peers"

    at Client._readError (/home/delegatex/lisk-test/node_modules/pg-native/index.js:80:13)
    at Client._read (/home/delegatex/lisk-test/node_modules/pg-native/index.js:121:19)
    at PQ.emit (events.js:104:17)
[ERR] 2016-11-28 14:35:44 | Failed to sweep peers - Error: ERROR:  deadlock detected
DETAIL:  Process 4016 waits for ShareLock on transaction 1770130; blocked by process 4019.
Process 4019 waits for ShareLock on transaction 1770132; blocked by process 4016.
HINT:  See server log for query details.
CONTEXT:  while inserting index tuple (6,54) in relation "peers"

    at Client._readError (/home/delegatex/lisk-test/node_modules/pg-native/index.js:80:13)
    at Client._read (/home/delegatex/lisk-test/node_modules/pg-native/index.js:121:19)
    at PQ.emit (events.js:104:17)
[ERR] 2016-11-28 14:35:45 | Failed to sweep peers - Error: ERROR:  deadlock detected
DETAIL:  Process 3983 waits for ShareLock on transaction 1770130; blocked by process 4019.
Process 4019 waits for ShareLock on transaction 1770133; blocked by process 3983.
HINT:  See server log for query details.
CONTEXT:  while inserting index tuple (3,114) in relation "peers"

    at Client._readError (/home/delegatex/lisk-test/node_modules/pg-native/index.js:80:13)
    at Client._read (/home/delegatex/lisk-test/node_modules/pg-native/index.js:121:19)
    at PQ.emit (events.js:104:17)
```

That's it. The client stopped working - no more logs came in.

**Comment by karmacoma** [comment]
> My node got some fork 1. I waited 5-10 minutes to let it recover by itself but it seemed like it couldn't recover. Then I did a manual reload. After the reload the log showed:

Automatic fork recovery has been fixed. Will push the changes today.

Second problem of deadlock is occurring as a result of database transacion overlap. I will fix.
