### ISSUE TITLE
Mainnet syncing and snapshotting failed for 1.6.0-alpha.4

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#3242]
### Expected behavior
Syncing and Snapshotting should succeed.
### Actual behavior
Snapshotting error
```
[ERR] 2019-04-02 02:49:31 | error: current transaction is aborted, commands ignored until end of transaction block
    at Connection.parseE (/home/lisk/lisk-1.6.0-alpha.4-4f10a53-Linux-x86_64/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/lisk/lisk-1.6.0-alpha.4-4f10a53-Linux-x86_64/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/home/lisk/lisk-1.6.0-alpha.4-4f10a53-Linux-x86_64/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
```
[ERR] 2019-04-02 02:49:31 | Snapshot creation failed - {"data":[{"success":false,"result":"Account#merge error"}
{"name":"error","length":144,"severity":"ERROR","code":"25P02","file":"postgres.c","line":"1022","routine":"exec_simple_query"}
```

Syncing error:
```
[ERR] 2019-04-02 05:34:39 | error: value "17179869184005050000" is out of range for type bigint
    at Connection.parseE (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[ERR] 2019-04-02 05:34:39 | error: current transaction is aborted, commands ignored until end of transaction block
    at Connection.parseE (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
```
### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0

**Comment by ManuGowda** [comment]
Before:
https://github.com/LiskHQ/lisk/blob/d7822d9be99fcc4f5812606906575083a22b6d0b/helpers/round_changes.js#L33-L81 (edited) 
After:
https://github.com/LiskHQ/lisk/blob/42b96432373868eb4e094699bc7a51931f64ac32/framework/src/modules/chain/logic/round.js#L306-L341
