### ISSUE TITLE
Wrong dapp transaction type

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#4]
With one of the last commits the transaction types were revised. 
The lisk-cli tool must also be updated, it creates still invalid entries in the genesis with "type": 9, this must be changed to the new dapp type 5.

**Comment by karmacoma** [comment]
Thanks for reporting :+1:

Issue has been resolved in the respective lisk-cli and lisk-js repositories. Subject to further testing.

- https://github.com/LiskHQ/lisk-cli
- https://github.com/LiskHQ/lisk-js

**Comment by TheGoldenEye** [comment]
After creation of a new dapp (lisk-cli dapps -a) a get the following error:
```
$ node app.js 
log 2016-03-22 21:02:31 Lisk started: 0.0.0.0:7000 
error 2016-03-22 21:02:39 saveBlock Unknown transaction type: 9
fatal 2016-03-22 21:02:39 Unknown transaction type: 9 

```
The reason seems the wrong dapp transaction type in genesisBlock.json:
 ```
      {
            "type": 9,
            "amount": 0,
            "fee": 0,
            "timestamp": 0,
            "recipientId": null,
            "senderId": "4599231408004878273L",
            "senderPublicKey": "67d3b5eaf0c0bf6b5a602d359daecc86a7a74053490ec37ae08e71360587c870",
            "asset": {
                "dapp": {
                    "name": "dapp1",
``` 

If I change the type to 5, I get a new error:
```
$ node app.js 
log 2016-03-22 21:09:31 Lisk started: 0.0.0.0:7000 
info 2016-03-22 21:09:31 Modules ready and launched 
info 2016-03-22 21:09:31 Blocks 1 
info 2016-03-22 21:09:31 Current 0 
fatal 2016-03-22 21:09:32 Domain master { message: 'Cannot read property \'name\' of undefined',
  stack: 'TypeError: Cannot read property \'name\' of undefined\n    at Transaction.DApp.applyUnconfirmed (/home/jens/src/coins/lisk_my/lisk/modules/dapps.js:551:46)\n    at Transaction.<anonymous> (/home/jens/src/coins/lisk_my/lisk/logic/transaction.js:546:44)\n    at /home/jens/src/coins/lisk_my/lisk/logic/account.js:585:3\n    at Account.<anonymous> (/home/jens/src/coins/lisk_my/lisk/logic/account.js:639:3)\n    at Socket.<anonymous> (/home/jens/src/coins/lisk_my/lisk/node_modules/dblite/build/dblite.node.js:379:22)\n    at Socket.emit (events.js:107:17)\n    at readableAddChunk (_stream_readable.js:163:16)\n    at Socket.Readable.push (_stream_readable.js:126:10)\n    at Pipe.onread (net.js:540:20)' }
error 2016-03-22 21:09:32 null 
info 2016-03-22 21:09:32 Cleaning up... 
```

The last one could be a result of removed UserNames?

**Comment by karmacoma** [comment]
@TheGoldenEye I haven't published the latest version of lisk-cli yet, as I don't want to break functionality of published packages. You can install the latest version from GitHub like so:

```bash
git clone git@github.com:LiskHQ/lisk-cli.git
cd lisk-cli
npm install -g .
```

Here you will see I've fixed the problems you described.
