### ISSUE TITLE
dapp is not defined

### ISSUE THREAD

**Issue by senikk** [LiskHQ/lisk#6]
Running node app.js suddenly resulted in 

> Domain master { message: 'dapp is not defined', stack: 'ReferenceError: dapp is not defined\n    at /var/lisk/lisk/app.js:7:1031\n    at /var/lisk/lisk/node_modules/async/lib/async.js:52:16\n    at iterate (/var/lisk/lisk/node_modules/async/lib/async.js:260:24)\n    at Object.async.forEachOfSeries.async.eachOfSeries (/var/lisk/lisk/node_modules/async/lib/async.js:281:9)\n    at Object.async.forEachSeries.async.eachSeries (/var/lisk/lisk/node_modules/async/lib/async.js:214:22)\n    at Object.B.launchApp (/var/lisk/lisk/app.js:7:606)\n    at /var/lisk/lisk/app.js:6:31259\n    at FSReqWrap.oncomplete (fs.js:95:15)' }

**Comment by senikk** [comment]
Solved. In my case I had wrong JSON formatting of the foreignKeys section in blockchain.js causing this error message.
