### ISSUE TITLE
npm test fails on master 

### ISSUE THREAD

**Issue by ab320012** [LiskHQ/lisk#794]
I am seeing npm test failing with the following stack trace: 

```

module.js:491
>>     throw err;
>>     ^
>> 
>> Error: Cannot find module 'js-nacl'
>>     at Function.Module._resolveFilename (module.js:489:15)
>>     at Function.Module._load (module.js:439:25)
>>     at Module.require (module.js:517:17)
>>     at require (internal/module.js:11:18)
>>     at Object.<anonymous> (/Users/ab/dev/lisk/test/lisk-js/index.js:8:22)
>>     at Module._compile (module.js:573:30)
>>     at Object.Module._extensions..js (module.js:584:10)
>>     at Object.Module._extensions.(anonymous function) [as .js] (/Users/ab/dev/lisk/node_modules/istanbul/lib/hook.js:109:37)
>>     at Module.load (module.js:507:32)
>>     at tryModuleLoad (module.js:470:12)
>>     at Function.Module._load (module.js:462:3)
>>     at Module.require (module.js:517:17)
>>     at require (internal/module.js:11:18)
>>     at Object.<anonymous> (/Users/ab/dev/lisk/test/node.js:23:13)
>>     at Module._compile (module.js:573:30)
>>     at Object.Module._extensions..js (module.js:584:10)
>>     at Object.Module._extensions.(anonymous function) [as .js] (/Users/ab/dev/lisk/node_modules/istanbul/lib/hook.js:109:37)
>>     at Module.load (module.js:507:32)
>>     at tryModuleLoad (module.js:470:12)
>>     at Function.Module._load (module.js:462:3)
>>     at Module.require (module.js:517:17)
>>     at require (internal/module.js:11:18)
>>     at Object.<anonymous> (/Users/ab/dev/lisk/test/common/initModule.js:9:13)
>>     at Module._compile (module.js:573:30)
>>     at Object.Module._extensions..js (module.js:584:10)
>>     at Object.Module._extensions.(anonymous function) [as .js] (/Users/ab/dev/lisk/node_modules/istanbul/lib/hook.js:109:37)
>>     at Module.load (module.js:507:32)
>>     at tryModuleLoad (module.js:470:12)
>>     at Function.Module._load (module.js:462:3)
>>     at Module.require (module.js:517:17)
>>     at require (internal/module.js:11:18)
>>     at Object.<anonymous> (/Users/ab/dev/lisk/test/unit/sql/blockRewards.js:8:21)
>>     at Module._compile (module.js:573:30)
>>     at Object.Module._extensions..js (module.js:584:10)
>>     at Object.Module._extensions.(anonymous function) [as .js] (/Users/ab/dev/lisk/node_modules/istanbul/lib/hook.js:109:37)
>>     at Module.load (module.js:507:32)
>>     at tryModuleLoad (module.js:470:12)
>>     at Function.Module._load (module.js:462:3)
>>     at Module.require (module.js:517:17)
>>     at require (internal/module.js:11:18)
>>     at Object.<anonymous> (/Users/ab/dev/lisk/test/index.js:3:1)
>>     at Module._compile (module.js:573:30)
>>     at Object.Module._extensions..js (module.js:584:10)
>>     at Object.Module._extensions.(anonymous function) [as .js] (/Users/ab/dev/lisk/node_modules/istanbul/lib/hook.js:109:37)
>>     at Module.load (module.js:507:32)
>>     at tryModuleLoad (module.js:470:12)
>>     at Function.Module._load (module.js:462:3)
>>     at Module.require (module.js:517:17)
>>     at require (internal/module.js:11:18)
>>     at /Users/ab/dev/lisk/node_modules/mocha/lib/mocha.js:222:27
>>     at Array.forEach (<anonymous>)
>>     at Mocha.loadFiles (/Users/ab/dev/lisk/node_modules/mocha/lib/mocha.js:219:14)
>>     at Mocha.run (/Users/ab/dev/lisk/node_modules/mocha/lib/mocha.js:487:10)
>>     at Object.<anonymous> (/Users/ab/dev/lisk/node_modules/mocha/bin/_mocha:459:18)
>>     at Module._compile (module.js:573:30)
>>     at Object.Module._extensions..js (module.js:584:10)
>>     at Object.Module._extensions.(anonymous function) [as .js] (/Users/ab/dev/lisk/node_modules/istanbul/lib/hook.js:109:37)
>>     at Module.load (module.js:507:32)
>>     at tryModuleLoad (module.js:470:12)
>>     at Function.Module._load (module.js:462:3)
>>     at Function.Module.runMain (module.js:609:10)
>>     at runFn (/Users/ab/dev/lisk/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
>>     at /Users/ab/dev/lisk/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
>>     at /Users/ab/dev/lisk/node_modules/istanbul/lib/util/file-matcher.js:68:16
>>     at /Users/ab/dev/lisk/node_modules/istanbul/node_modules/async/lib/async.js:52:16
>>     at /Users/ab/dev/lisk/node_modules/istanbul/node_modules/async/lib/async.js:361:13
>>     at /Users/ab/dev/lisk/node_modules/istanbul/node_modules/async/lib/async.js:52:16
>>     at done (/Users/ab/dev/lisk/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
>>     at /Users/ab/dev/lisk/node_modules/istanbul/node_modules/async/lib/async.js:44:16
>>     at /Users/ab/dev/lisk/node_modules/istanbul/node_modules/async/lib/async.js:358:17
>>     at LOOP (fs.js:1753:14)
>>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>>     at process._tickCallback (internal/process/next_tick.js:180:9)
```
wondering if tests weren't updated when changing from js-nacl to sodium or if there is something wrong with my install.

**Comment by ab320012** [comment]
trying to write a passing test for: https://github.com/LiskHQ/lisk/issues/781

should be simple call in modules/delegates.js:

**Comment by karmacoma** [comment]
@ab320012 Please try running `npm install` in `test/lisk-js`.

Note: In development branch this is no longer required.

**Comment by diego-G** [comment]
PR 856 fixes and checks all the scripts execute properly. Also it introduces new scripts to run each testsuite independently.

**Comment by karmacoma** [comment]
Closing issue as `lisk-js` submodule has been removed in `1.0.0`.
