### ISSUE TITLE
Fix unstable tests for data from a real peer

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#961]
### Expected behaviour

Tests always pass.

### Actual behaviour

Tests fail when testing data passed from a "real" peer.

```
1) GET /peers
       pass data from a real peer
         using version = "0.0.0a" should return the result:
     TypeError: Cannot read property 'version' of undefined
    at test/functional/http/get/peers.js:115:22
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
  

  2) GET /peers
       pass data from a real peer
         using limit = 1 and offset = 1 should be ok:
     TypeError: Cannot read property 'should' of undefined
    at test/functional/http/get/peers.js:155:22
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

### Steps to reproduce

Runs whole test-suite locally or on Jenkins.

**Comment by nazarhussain** [comment]
There is some difference in between `Mac` and `Linux` behaviour. 

Added this line 
```
// modules/peers.js:491
library.logger.debug('Listing peers', library.logic.peers.list(true));
```

So on jenkins we get 

```
[dbg] 2017-12-14 10:35:21 | Listing peers - [{"ip":"127.0.0.1","wsPort":3903,"state":1,"os":"debian","version":"0.0.9","broadhash":"198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d","height":1,"clock":null,"updated":1513247717609,"nonce":"eIYYZXhjDxW5vRjm","httpPort":53140},{"ip":"127.0.0.1","wsPort":34046,"state":1,"os":"win32","version":"0.0.2","broadhash":"198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d","height":1,"clock":null,"updated":1513247718644,"nonce":"JOnYCeCXGRr9Rj9h","httpPort":24614}]
```

Notice `"state":1` which is for disconnected, this appears even if tests passes on jenkins. While on mac machines it always have `"state":2` means connected.

**Comment by nazarhussain** [comment]
I figure out another use case where these test cases can fail. The issue is with the order starting the ws server and ws client. During tests since we are starting up ws server in a seperate process and we are not sure when the its ready to accept the connections. So we just take a hunch and start the ws client after 1sec. If ws server start before 1 sec then all good, if it took longer and during that time main lisk instance try to reach it and it do not respond, its state been converted to disconnected, which causes the failure of the tests. 

Had made some changes to ws server master file, to handle this scenario and only connect the client to lisk after server is ready to accept the connections.
